clear;
close all;
r0=0.001;
rb=3; %radius of the initial sphere
p=-0; %-0.555; pressure (out-in)
%p=-2*sigma_e/rb;  % Young-Laplace equation for a sphere
kappa0=1;      % kappa_m bending rigidity of the base
kappa2 = 2;    % kappa_p bending rigidity of the anisotropic proteins
psi0=pi;       % psi(u=1) fixed hinge
fSharp=100;    % slope of the tanhx
ag1start = 0.5;  % position of the proteins A_1
ag2start = 0.68; % position of the proteins A_2
ap=1;
ag1 = ag1start;
ag2 = ag2start;

C01 = 0;  % spontaneous curvature of the base

nmax = 20; 
RTol = 1e-5;    

% fH(j,:) = [usefulC02,Hprotrusion0,ag1,ag2,simps(u,totalenergy),simps(u,bendenergy),simps(u,pressureenergy),theta];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% load the solution generated by MainCode1.m
DIR = pwd;
filename = [DIR,'\Initial_kappa0_1_kappa2_2_ap_1_fSharp_100_thetamax_0_p_0_C02begin_0_C02end_16_C02max_22.1962_ag1begin_0.5_ag2begin_0.68_nmax_20_rb_3_RTol_0.0001_date_19-Nov-2024.mat'];

load(filename);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fH=sol_all{1};
soldifferentcurvature=sol_all{2};
C02all=fH(:,1);
idx33 = 770;
C02=fH(idx33,1);
thetastart=fH(idx33,8);
sol = soldifferentcurvature(idx33);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h0=sol.parameters(1);
sol.parameters=[h0];
varc = thetastart:-0.001:0; 
fHtheta = [];
dynamicthetaSOL=[];
kk = 0;
for theta = varc
   usefultheta=theta;
    yeq = @(u,y,para)shape1(u,y,para,fSharp,ag1,ag2,C01,C02,kappa0,kappa2,p,ap,theta);
    ybc = @(ya,yb,para)twobc1(ya,yb,para,r0,rb,psi0,C01,C02,fSharp,ag1,ag2,kappa0,kappa2,p,ap,theta);
    opts = bvpset('RelTol',RTol,'AbsTol',1e-10,'NMax',50000);
    soltemp = bvp5c(yeq,ybc,sol,opts); 

    if soltemp.stats.maxerr < RTol
        kk=kk+1;
        sol=soltemp;  

    else 
        usefultheta=theta-(varc(2)-varc(1)); 
        break;
    end

    figure(1);
    r = sol.y(3,:);
    z = sol.y(4,:);
    area11=sol.y(9,:);
    areaC0=ag2-ag1;
    position=(ag2+ag1)/2;
    Hprotrusion0=sol.y(4,1);
    dpsi= sol.y(2,:);
    h=sol.parameters(1);
    psi=sol.y(1,:);
    area=sol.y(9,:);
    u=sol.x;
    [C02,usefultheta,Hprotrusion0]
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
totalenergy=(1/2).*h.*p.*r.^2.*sin(psi)+(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.* ...
  h.^(-1)+r.^(-1).*sin(psi)).^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+ ...
  r.^(-1).*cos(theta).^2.*sin(psi)+dpsi.*h.^(-1).*sin(theta).^2) ...
  .^2.*(tanh(((-1).*ag1+area).*fSharp)+(-1).*tanh(((-1).*ag2+area).* ...
  fSharp));
bendenergy=(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.*h.^(-1)+r.^(-1).*sin(psi)) ...
  .^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+r.^(-1).*cos(theta).^2.* ...
  sin(psi)+dpsi.*h.^(-1).*sin(theta).^2).^2.*(tanh(((-1).*ag1+area) ...
  .*fSharp)+(-1).*tanh(((-1).*ag2+area).*fSharp));
pressureenergy=(1/2).*h.*p.*r.^2.*sin(psi);
    [~,idx1]=min(abs(area11-ag1));   
    [~,idx2]=min(abs(area11-ag2));   
    plot(r(1:idx1),z(1:idx1),'k',-r(1:idx1),z(1:idx1),'k','LineWidth',3);
    hold on
    plot(r(idx1:idx2),z(idx1:idx2),'g.',-r(idx1:idx2),z(idx1:idx2),'g.','LineWidth',3);
    plot(r(idx2:end),z(idx2:end),'k',-r(idx2:end),z(idx2:end),'k','LineWidth',3);
    axis equal;  
    title(['C0_{2} = ',num2str(C02),',','areaC0 = ',num2str(areaC0),newline,'ag_{1} = ',num2str(ag1),',','ag_{2} = ',num2str(ag2),',','position = ',num2str(0.5*(ag1+ag2)),',','H = ',num2str(sol.y(4,1)),',','theta = ',num2str(theta)]);
    xlabel('r','FontSize',26,'FontName','Times');
    ylabel('z','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5)
    set(figure(1), 'Color', 'white');
    drawnow;
    hold off; 
    areasphere=sol.y(9,end);
    fHtheta(kk,:) = [C02,Hprotrusion0,ag1,ag2,simps(u,totalenergy),simps(u,bendenergy),simps(u,pressureenergy),theta];
    dynamicthetaSOL = [dynamicthetaSOL sol];
end 
theta=usefultheta; 
 figure(111);
    plot(fHtheta(:,8),fHtheta(:,2),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Hsphere','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(111), 'Color', 'white');
     figure(1111);
    plot(fHtheta(:,8),fHtheta(:,5),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Totalenergy','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(1111), 'Color', 'white');

h0=sol.parameters(1);
% theta=fH(end,8);   
Hinitial=fHtheta(end,2);  
sol.parameters=[h0,theta]; 
varc = Hinitial:0.0001:10;  
for H = varc   
    yeq = @(u,y,para) shape4(u,y,para,fSharp,ag1,ag2,C01,kappa0,kappa2,p,ap,C02);
    ybc = @(ya,yb,para)twobc4(ya,yb,para,r0,rb,psi0,C01,fSharp,ag1,ag2,kappa0,kappa2,H,p,ap,C02);
    opts = bvpset('RelTol',1e-6,'AbsTol',1e-10,'NMax',50000);
    soltemp = bvp5c(yeq,ybc,sol,opts);       
    if soltemp.stats.maxerr < RTol
            kk=kk+1;
          sol=soltemp;       
    figure(1);
    r = sol.y(3,:);
    z = sol.y(4,:);
    area11=sol.y(9,:);
    areaC0=ag2-ag1;
    position=(ag2+ag1)/2;
    Hprotrusion0=sol.y(4,1);
    theta=sol.parameters(2);
    [C02,theta,Hprotrusion0]
    %%%%%%%%%%%%%%%%%%%%%%%%%%%
    dpsi= sol.y(2,:);
    h=sol.parameters(1);
    psi=sol.y(1,:);
    area=sol.y(9,:);
    u=sol.x;
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
totalenergy=(1/2).*h.*p.*r.^2.*sin(psi)+(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.* ...
  h.^(-1)+r.^(-1).*sin(psi)).^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+ ...
  r.^(-1).*cos(theta).^2.*sin(psi)+dpsi.*h.^(-1).*sin(theta).^2) ...
  .^2.*(tanh(((-1).*ag1+area).*fSharp)+(-1).*tanh(((-1).*ag2+area).* ...
  fSharp));
bendenergy=(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.*h.^(-1)+r.^(-1).*sin(psi)) ...
  .^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+r.^(-1).*cos(theta).^2.* ...
  sin(psi)+dpsi.*h.^(-1).*sin(theta).^2).^2.*(tanh(((-1).*ag1+area) ...
  .*fSharp)+(-1).*tanh(((-1).*ag2+area).*fSharp));
pressureenergy=(1/2).*h.*p.*r.^2.*sin(psi);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    fHtheta(kk,:) = [C02,Hprotrusion0,ag1,ag2,simps(u,totalenergy),simps(u,bendenergy),simps(u,pressureenergy),theta];
    dynamicthetaSOL=[dynamicthetaSOL sol];
    [~,idx1]=min(abs(area11-ag1));   
    [~,idx2]=min(abs(area11-ag2));   
    plot(r(1:idx1),z(1:idx1),'k',-r(1:idx1),z(1:idx1),'k','LineWidth',3);
    hold on
    plot(r(idx1:idx2),z(idx1:idx2),'g',-r(idx1:idx2),z(idx1:idx2),'g','LineWidth',3);
    hold on
    plot(r(idx2:end),z(idx2:end),'k',-r(idx2:end),z(idx2:end),'k','LineWidth',3);
    axis equal;  
    % ylim([0 6]);      
    % xlim([-4 4]);

    title(['C0_{2} = ',num2str(C02),',','areaC0 = ',num2str(areaC0),newline,'ag_{1} = ',num2str(ag1),',','ag_{2} = ',num2str(ag2),',','position = ',num2str(0.5*(ag1+ag2)),',','H = ',num2str(sol.y(4,1)),',','theta = ',num2str(theta)]);
    xlabel('r','FontSize',26,'FontName','Times');
    ylabel('z','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5)
    set(figure(1), 'Color', 'white');
    drawnow;
    hold off; 
    areasphere=sol.y(9,end);

    else
        break;
    end
    if theta<0
        break;
    end
    if theta>1.57
        break;
    end
end
%%%%%%%%%%%%%%
 figure(222);
    plot(fHtheta(:,8),fHtheta(:,2),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Hsphere','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(222), 'Color', 'white');
     figure(2222);
    plot(fHtheta(:,8),fHtheta(:,5),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Totalenergy','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(2222), 'Color', 'white');
%%%%%%%%%%%%%%
h0=sol.parameters(1);
thetachushi=fHtheta(end,8);   
sol.parameters=[h0]; 
if  fHtheta(end-1,8)<fHtheta(end,8)
    varc = thetachushi:0.0002:1.57;  
else
    varc = thetachushi:-0.0002:0;  
end
for theta = varc
   usefultheta=theta;
    yeq = @(u,y,para)shape1(u,y,para,fSharp,ag1,ag2,C01,C02,kappa0,kappa2,p,ap,theta);
    ybc = @(ya,yb,para)twobc1(ya,yb,para,r0,rb,psi0,C01,C02,fSharp,ag1,ag2,kappa0,kappa2,p,ap,theta);
    opts = bvpset('RelTol',RTol,'AbsTol',1e-10,'NMax',50000);
    soltemp = bvp5c(yeq,ybc,sol,opts); 

    if soltemp.stats.maxerr < RTol
        kk=kk+1;
        sol=soltemp;  

    else 
        usefultheta=theta-(varc(2)-varc(1)); 
        break;
    end

    figure(1);
    r = sol.y(3,:);
    z = sol.y(4,:);
    area11=sol.y(9,:);
    areaC0=ag2-ag1;
    position=(ag2+ag1)/2;
    Hprotrusion0=sol.y(4,1);
    dpsi= sol.y(2,:);
    h=sol.parameters(1);
    psi=sol.y(1,:);
    area=sol.y(9,:);
    u=sol.x;
    [C02,usefultheta,Hprotrusion0]
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
totalenergy=(1/2).*h.*p.*r.^2.*sin(psi)+(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.* ...
  h.^(-1)+r.^(-1).*sin(psi)).^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+ ...
  r.^(-1).*cos(theta).^2.*sin(psi)+dpsi.*h.^(-1).*sin(theta).^2) ...
  .^2.*(tanh(((-1).*ag1+area).*fSharp)+(-1).*tanh(((-1).*ag2+area).* ...
  fSharp));
bendenergy=(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.*h.^(-1)+r.^(-1).*sin(psi)) ...
  .^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+r.^(-1).*cos(theta).^2.* ...
  sin(psi)+dpsi.*h.^(-1).*sin(theta).^2).^2.*(tanh(((-1).*ag1+area) ...
  .*fSharp)+(-1).*tanh(((-1).*ag2+area).*fSharp));
pressureenergy=(1/2).*h.*p.*r.^2.*sin(psi);
    [~,idx1]=min(abs(area11-ag1));   
    [~,idx2]=min(abs(area11-ag2));   
    plot(r(1:idx1),z(1:idx1),'k',-r(1:idx1),z(1:idx1),'k','LineWidth',3);
    hold on
    plot(r(idx1:idx2),z(idx1:idx2),'g.',-r(idx1:idx2),z(idx1:idx2),'g.','LineWidth',3);
    plot(r(idx2:end),z(idx2:end),'k',-r(idx2:end),z(idx2:end),'k','LineWidth',3);
    axis equal;  
    title(['C0_{2} = ',num2str(C02),',','areaC0 = ',num2str(areaC0),newline,'ag_{1} = ',num2str(ag1),',','ag_{2} = ',num2str(ag2),',','position = ',num2str(0.5*(ag1+ag2)),',','H = ',num2str(sol.y(4,1)),',','theta = ',num2str(theta)]);
    xlabel('r','FontSize',26,'FontName','Times');
    ylabel('z','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5)
    set(figure(1), 'Color', 'white');
    drawnow;
    hold off; 
    areasphere=sol.y(9,end);
    fHtheta(kk,:) = [C02,Hprotrusion0,ag1,ag2,simps(u,totalenergy),simps(u,bendenergy),simps(u,pressureenergy),theta];
    dynamicthetaSOL = [dynamicthetaSOL sol];
    if theta<0
        break;
    end
    if theta>1.57
        break;
    end
end 
theta=usefultheta; 
 figure(333);
    plot(fHtheta(:,8),fHtheta(:,2),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Hsphere','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(333), 'Color', 'white');
     figure(3333);
    plot(fHtheta(:,8),fHtheta(:,5),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Totalenergy','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(3333), 'Color', 'white');
% %%%%%%%%%%%%

h0=sol.parameters(1);
% theta=fH(end,8);   
Hinitial=fHtheta(end,2);  
sol.parameters=[h0,theta]; 
if  fHtheta(end-1,2)<fHtheta(end,2)
    varc = Hinitial:0.0001:10;  
else
    varc = Hinitial:-0.0001:0;  
end
for H = varc   
    yeq = @(u,y,para) shape4(u,y,para,fSharp,ag1,ag2,C01,kappa0,kappa2,p,ap,C02);
    ybc = @(ya,yb,para)twobc4(ya,yb,para,r0,rb,psi0,C01,fSharp,ag1,ag2,kappa0,kappa2,H,p,ap,C02);
    opts = bvpset('RelTol',1e-6,'AbsTol',1e-10,'NMax',50000);
    soltemp = bvp5c(yeq,ybc,sol,opts);       
    if soltemp.stats.maxerr < RTol
            kk=kk+1;
          sol=soltemp;       
    figure(1);
    r = sol.y(3,:);
    z = sol.y(4,:);
    area11=sol.y(9,:);
    areaC0=ag2-ag1;
    position=(ag2+ag1)/2;
    Hprotrusion0=sol.y(4,1);
    theta=sol.parameters(2);
    [C02,theta,Hprotrusion0]
    %%%%%%%%%%%%%%%%%%%%%%%%%%%
    dpsi= sol.y(2,:);
    h=sol.parameters(1);
    psi=sol.y(1,:);
    area=sol.y(9,:);
    u=sol.x;
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
totalenergy=(1/2).*h.*p.*r.^2.*sin(psi)+(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.* ...
  h.^(-1)+r.^(-1).*sin(psi)).^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+ ...
  r.^(-1).*cos(theta).^2.*sin(psi)+dpsi.*h.^(-1).*sin(theta).^2) ...
  .^2.*(tanh(((-1).*ag1+area).*fSharp)+(-1).*tanh(((-1).*ag2+area).* ...
  fSharp));
bendenergy=(1/2).*h.*kappa0.*r.*((-1).*C01+dpsi.*h.^(-1)+r.^(-1).*sin(psi)) ...
  .^2+(1/4).*ap.*h.*kappa2.*r.*((-1).*C02+r.^(-1).*cos(theta).^2.* ...
  sin(psi)+dpsi.*h.^(-1).*sin(theta).^2).^2.*(tanh(((-1).*ag1+area) ...
  .*fSharp)+(-1).*tanh(((-1).*ag2+area).*fSharp));
pressureenergy=(1/2).*h.*p.*r.^2.*sin(psi);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    fHtheta(kk,:) = [C02,Hprotrusion0,ag1,ag2,simps(u,totalenergy),simps(u,bendenergy),simps(u,pressureenergy),theta];
    dynamicthetaSOL=[dynamicthetaSOL sol];
    [~,idx1]=min(abs(area11-ag1));   
    [~,idx2]=min(abs(area11-ag2));   
    plot(r(1:idx1),z(1:idx1),'k',-r(1:idx1),z(1:idx1),'k','LineWidth',3);
    hold on
    plot(r(idx1:idx2),z(idx1:idx2),'g',-r(idx1:idx2),z(idx1:idx2),'g','LineWidth',3);
    hold on
    plot(r(idx2:end),z(idx2:end),'k',-r(idx2:end),z(idx2:end),'k','LineWidth',3);
    axis equal;  
    % ylim([0 6]);      
    % xlim([-4 4]);

    title(['C0_{2} = ',num2str(C02),',','areaC0 = ',num2str(areaC0),newline,'ag_{1} = ',num2str(ag1),',','ag_{2} = ',num2str(ag2),',','position = ',num2str(0.5*(ag1+ag2)),',','H = ',num2str(sol.y(4,1)),',','theta = ',num2str(theta)]);
    xlabel('r','FontSize',26,'FontName','Times');
    ylabel('z','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5)
    set(figure(1), 'Color', 'white');
    drawnow;
    hold off; 
    areasphere=sol.y(9,end);

    else
        break;
    end
    if theta<0
        break;
    end
    if theta>1.57
        break;
    end
end
%%%%%%%%%%%%%%
 figure(444);
    plot(fHtheta(:,8),fHtheta(:,2),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Hsphere','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(444), 'Color', 'white');
     figure(4444);
    plot(fHtheta(:,8),fHtheta(:,5),'k.-');
    title(['C0_{2}=',num2str(C02),',','areaC02=',num2str(areaC0)]);
    xlabel('theta','FontSize',26,'FontName','Times');
    ylabel('Totalenergy','FontSize',26,'FontName','Times');
    set(gca,'FontName','Times New Roman','FontSize',26,'LineWidth',2.5);
    set(figure(4444), 'Color', 'white');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%save the data
 DIR = pwd; 
filename = [DIR,'/uptobottom_vary_theta_kappa0_',num2str(kappa0),...
    '_kappa2_',num2str(kappa2),...
    '_ap_',num2str(ap),...
    '_p_',num2str(p),...
    '_C02_',num2str(C02),...
    '_ag1_',num2str(ag1),...
    '_ag2_',num2str(ag2),...
    '_nmax_',num2str(nmax),...
    '_rb_',num2str(rb),...
    '_RTol_',num2str(RTol),...
    '_date_',date,'.mat'];
sol_all = cell(1,2); 

    sol_all{1,1} = fHtheta;
    sol_all{1,2} =  dynamicthetaSOL;

    save(filename,'sol_all');


  